url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/biblio-sphere" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
# remote_theme: pages-themes/modernist@v0.2.0

collections:
    authors:
        output: true

defaults:
    - scope:
          path: ""
          type: "authors"
      values:
          layout: "author"
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
    - scope:
          path: ""
      values:
          layout: "default"

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-remote-theme
